updated auto merge

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -29,6 +29,24 @@ jobs:
           pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
           pr_body: "Automated Pull Request"
 
+      - name: Auto approve
+        if: steps.open-pr.outputs.pr_number != ''
+        uses: juliangruber/approve-pull-request-action@v2
+        with:
+          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          number: ${{ steps.open-pr.outputs.pr_number }}
+        continue-on-error: true
+
+      - name: Check approval result
+        run: |
+          if [ "${{ steps.open-pr.outputs.pr_number.outcome }}" == "success" ]; then
+            echo "✅ PR approved successfully!"
+          else
+            echo "❌ Failed to auto approve the PR"
+            exit 1
+          fi
+  
+
       # https://github.com/marketplace/actions/enable-pull-request-automerge
       - name: Enable Automerge
         if: steps.open-pr.outputs.pr_number != ''
@@ -37,10 +55,28 @@ jobs:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
           pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
           merge-method: squash
+
+      - name: Check Automerge Result
+        run: |
+          if [ "${{ steps.open-pr.outputs.pr_number.outcome }}" == "success" ]; then
+            echo "✅ Auto-merge enabled successfully!"
+          else
+            echo "❌ Failed to enable auto-merge on PR"
+            exit 1
+          fi
+        
+      - name: Delete source branch
+        if: steps.open-pr.outputs.pr_number.outcome == 'success'
+        run: |
+          BRANCH_NAME="${GITHUB_REF##*/}"
+          echo "🔄 Deleting branch: $BRANCH_NAME"
       
-      - name: Auto approve
-        if: steps.open-pr.outputs.pr_number == 'created'
-        uses: juliangruber/approve-pull-request-action@v2
-        with:
-          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          number: ${{ steps.open-pr.outputs.pr_number }}
+          gh auth login --with-token <<< "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
+          gh api \
+            -X DELETE \
+            "repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
+      
+          echo "✅ Branch '$BRANCH_NAME' deleted."
+        env:
+          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          
